name: 'Pytest'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  pytest:
    name: 'Pytest'
    runs-on: ubuntu-latest
    environment: alpha

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      working-directory: ./pandas
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      working-directory: ./pandas
      run: make test
